# -*- coding: utf-8 -*-
"""Resume Screening.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R1DLA7gdPN5AuMn7QF1OfaVAI_OvX0fc
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("/content/resume_screening_dataset.csv")
df.head()

# Check Data
df.shape
df['Category'].value_counts()

# Text Cleaning (NLP Preprocessing)
import re

def clean_text(text):
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    text = text.lower()
    text = text.split()
    return " ".join(text)

df['clean_resume'] = df['Resume'].apply(clean_text)
df.head()

# Encode Labels
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['label'] = le.fit_transform(df['Category'])
df.head()

# Convert Text → Numbers (TF-IDF)
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english', max_features=3000)
X = tfidf.fit_transform(df['clean_resume']).toarray()

y = df['label']

# Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train Model (Naive Bayes)
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

# Model Evaluation
from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

def predict_resume(text):
    cleaned = clean_text(text)
    vector = tfidf.transform([cleaned]).toarray()
    pred = model.predict(vector)
    return le.inverse_transform(pred)[0]

sample_resume = "Python Django Machine Learning Data Analysis SQL Pandas"

print("Predicted Category:", predict_resume(sample_resume))

